---
title: "Supplemental Table 2"
format: html
---

```{r}
library(dplyr)
library(gt)
```

```{r}
StorageLocation <- file.path("SupplementaryFigures/SupplementaryTable2")
Data <- read.csv("data/ILT_Antibody_Panels.csv", check.names = FALSE)
Data1 <- Data |> filter(Panel %in% "Conventional") |> select(-Panel) |> filter(Purpose %in% "Full") |> select(-Purpose)
Data2 <- Data |> filter(Panel %in% "Conventional") |> select(-Panel) |> filter(!Purpose %in% "Full") |> select(-Purpose)
Data <- bind_rows(Data1, Data2) #|> rename(Temperature = SubPanel)
```

```{r}
#| label: tbl-AntibodyPanels
#| tbl-cap: "Antibody Panels"
#| tbl-width: 3
#| out-width: "80%"
#| tbl-align: "left"
#| code-fold: true

gt_Data <- gt(Data)

gt_Data <- gt_Data |> tab_header( 
  title = md("**Supplemental Table 2: CFC Antibodies**"),
  subtitle = ""
  ) |> cols_label(SubPanel ~ md("SubPanel<sup>†</sup>")) |>
  tab_source_note(
    source_note = "Last Updated: May 08, 2025"
  ) |> tab_footnote(
    footnote = "† 1 = Phenotype, 2 = NK markers, 4b = Cytotoxicity, CK = Cytokine, 0 = ExVivo, 17 = Culture",
    locations = cells_column_labels(columns = SubPanel),
    placement = "left"
  )

Bolded <- gt_Data |> opt_table_font(font = "Montserrat") |> cols_align(align = "center") |>  cols_label(Alternate.Name ~ md('Alternate<br>name')) |>  cols_label(Catalog.Number ~ md('Catalog<br>number')) 


Bolded <- Bolded |> opt_table_outline(style="solid", width=px(2), color="black") |> tab_options(column_labels.border.top.style = "solid",
  column_labels.border.top.width = px(2), column_labels.border.top.color = "black", table.border.bottom.style = "double", table.border.bottom.width = px(2),
  table.border.bottom.color = "black",  table.font.size = 22)

FinalStorage <- file.path(StorageLocation, "SupplementalFigure2_CFC.html")

gtsave(Bolded, FinalStorage)

FinalStorage <- file.path(StorageLocation, "SupplementalFigure2_CFC_Comps.docx")

gtsave(Bolded, FinalStorage)
```

```{r}
print("Goodbye")
```

