---
title: "Reviewer Request - Perforin"
format: docx
---

# Code

```{r}
library(purrr)
library(Coereba)
library(ggplot2)
```

```{r}
#| code-fold: true
shape_sex <- c("Female" = 22, "Male" = 21)
fill_sex <- c("Female" = "white", "Male" = "black")

shape_ptype <- c("HU" = 22, "HEU-lo" = 21, "HEU-hi" = 21)
fill_ptype <- c("HU" = "white", "HEU-lo" = "darkgray", "HEU-hi" = "black")

shape_art <- c("HU" = 22, "HEU" = 21)
fill_art <- c("HU" = "white", "HEU" = "black")

shape_viral <- c("NoViral" = 22, "Viral" = 21)
fill_viral <- c("NoViral" = "white", "Viral" = "black")
```

# ExVivo

```{r}
StorageLocation <- file.path("Extra")
data <- read.csv("data/D0Perforin.csv")
data$ptype <- factor(data$ptype, levels=c("HU", "HEU-lo", "HEU-hi"))
data$infant_sex <- factor(data$infant_sex, levels=c("Female", "Male"))
str(data)

PlotName <- "D0Perforin"

ThePlot <- map(names(data)[5], ~ Utility_Behemoth(data = data, var = .x,
 myfactor = "ptype", normality = "dagostino", shape_palette = shape_ptype,
  fill_palette = fill_ptype, cex = 2, size = 3, corral.width = 1,
   statsHeight=70, scalePercent = FALSE, correction = "BH", keepNS=FALSE))

Plot <- ThePlot[[1]] + labs(y = NULL, title = NULL) +
     theme(plot.caption = element_blank(),
      axis.text.y = element_text(size = 15),
       axis.text.x= element_text(size = 15)) #+ lims(y=c(0,NA))

Plot

Abbreviation <- "_ptype.png"
ThePlotName <- paste0(PlotName, Abbreviation)
TheFile <- file.path(StorageLocation, ThePlotName)

ggsave(filename = TheFile, Plot, dpi = 600, width = 4, height = 3)
```



## IL2

```{r}
StorageLocation <- file.path("Extra")
data <- read.csv("data/gd_CFC_D17Phenotype_IL2ExpressionData.csv")
data$ptype <- factor(data$ptype, levels=c("HU", "HEU-lo", "HEU-hi"))
data$infant_sex <- factor(data$infant_sex, levels=c("Female", "Male"))

PlotName <- "D17PerforinIL2"

ThePlot <- map(names(data)[22], ~ Utility_Behemoth(data = data, var = .x,
 myfactor = "ptype", normality = "dagostino", shape_palette = shape_ptype,
  fill_palette = fill_ptype, cex = 2, size = 3, corral.width = 1,
   statsHeight=1, scalePercent = TRUE, correction = "BH", keepNS=FALSE))

Plot <- ThePlot[[1]] + labs(y = NULL, title = NULL) +
     theme(plot.caption = element_blank(),
      axis.text.y = element_text(size = 15),
       axis.text.x= element_text(size = 15)) #+ lims(y=c(0,NA))

Plot

Abbreviation <- "_ptype.png"
ThePlotName <- paste0(PlotName, Abbreviation)
TheFile <- file.path(StorageLocation, ThePlotName)

ggsave(filename = TheFile, Plot, dpi = 600, width = 4, height = 3)
```

## ZOL

```{r}
StorageLocation <- file.path("Extra")
data <- read.csv("data/gd_CFC_D17Phenotype_ZOLExpressionData.csv")
data$ptype <- factor(data$ptype, levels=c("HU", "HEU-lo", "HEU-hi"))
data$infant_sex <- factor(data$infant_sex, levels=c("Female", "Male"))

PlotName <- "D17PerforinZOL"

ThePlot <- map(names(data)[22], ~ Utility_Behemoth(data = data, var = .x,
 myfactor = "ptype", normality = "dagostino", shape_palette = shape_ptype,
  fill_palette = fill_ptype, cex = 2, size = 3, corral.width = 1,
   statsHeight=1, scalePercent = TRUE, correction = "BH", keepNS=FALSE))

Plot <- ThePlot[[1]] + labs(y = NULL, title = NULL) +
     theme(plot.caption = element_blank(),
      axis.text.y = element_text(size = 15),
       axis.text.x= element_text(size = 15)) #+ lims(y=c(0,NA))

Plot

Abbreviation <- "_ptype.png"
ThePlotName <- paste0(PlotName, Abbreviation)
TheFile <- file.path(StorageLocation, ThePlotName)

ggsave(filename = TheFile, Plot, dpi = 600, width = 4, height = 3)
```

## BCG

```{r}
StorageLocation <- file.path("Extra")
data <- read.csv("data/gd_CFC_D17Phenotype_BCGExpressionData.csv")
data$ptype <- factor(data$ptype, levels=c("HU", "HEU-lo", "HEU-hi"))
data$infant_sex <- factor(data$infant_sex, levels=c("Female", "Male"))

PlotName <- "D17PerforinBCG"

ThePlot <- map(names(data)[22], ~ Utility_Behemoth(data = data, var = .x,
 myfactor = "ptype", normality = "dagostino", shape_palette = shape_ptype,
  fill_palette = fill_ptype, cex = 2, size = 3, corral.width = 1,
   statsHeight=1, scalePercent = TRUE, correction = "BH", keepNS=FALSE))

Plot <- ThePlot[[1]] + labs(y = NULL, title = NULL) +
     theme(plot.caption = element_blank(),
      axis.text.y = element_text(size = 15),
       axis.text.x= element_text(size = 15)) #+ lims(y=c(0,NA))

Plot

Abbreviation <- "_ptype.png"
ThePlotName <- paste0(PlotName, Abbreviation)
TheFile <- file.path(StorageLocation, ThePlotName)

ggsave(filename = TheFile, Plot, dpi = 600, width = 4, height = 3)
```